const PACKS = {
  default: [
    "apple",
    "banana",
    "carrot",
    "elephant",
    "football",
    "guitar",
    "house",
    "internet",
    "jungle",
    "kangaroo",
    "laptop",
    "mountain",
    "notebook",
    "ocean",
    "piano",
    "quilt",
    "rocket",
    "sunflower",
    "train",
    "umbrella",
    "violin",
    "watermelon",
    "xylophone",
    "yacht",
    "zebra",
    "book",
    "camera",
    "candle",
    "chair",
    "clock",
    "door",
    "flower",
    "glasses",
    "hat",
    "key",
    "ladder",
    "mirror",
    "pencil",
    "pillow",
    "shoe",
    "spoon",
    "table",
    "tent",
    "wallet",
    "window",
  ],
  animals: [
    "elephant",
    "giraffe",
    "penguin",
    "dolphin",
    "kangaroo",
    "octopus",
    "flamingo",
    "hedgehog",
    "crocodile",
    "butterfly",
    "squirrel",
    "peacock",
    "koala",
    "walrus",
    "cheetah",
    "raccoon",
    "otter",
    "seahorse",
    "toucan",
    "platypus",
    "lion",
    "tiger",
    "panda",
    "rabbit",
    "turtle",
    "owl",
    "fox",
    "bat",
    "camel",
    "gorilla",
    "rhinoceros",
    "hippopotamus",
    "chameleon",
    "jellyfish",
    "armadillo",
  ],
  food: [
    "pizza",
    "burger",
    "sushi",
    "pancake",
    "spaghetti",
    "taco",
    "waffle",
    "sandwich",
    "popcorn",
    "cupcake",
    "avocado",
    "pretzel",
    "donut",
    "lemonade",
    "burrito",
    "noodles",
    "croissant",
    "milkshake",
    "pineapple",
    "meatball",
    "cheese",
    "chocolate",
    "cookie",
    "grapes",
    "hotdog",
    "icecream",
    "ketchup",
    "lasagna",
    "mango",
    "muffin",
    "omelette",
    "salad",
    "strawberry",
    "yogurt",
    "bacon",
  ],
  movies: [
    "superhero",
    "spaceship",
    "dinosaur",
    "wizard",
    "pirate",
    "robot",
    "vampire",
    "dragon",
    "ghost",
    "zombie",
    "detective",
    "astronaut",
    "ninja",
    "mermaid",
    "alien",
    "castle",
    "treasure",
    "volcano",
    "submarine",
    "time machine",
    "werewolf",
    "genie",
    "knight",
    "witch",
    "monster",
    "spy",
    "cowboy",
    "samurai",
    "sorcerer",
    "cyborg",
    "mummy",
    "unicorn",
    "phoenix",
    "kraken",
    "gladiator",
  ],
}

function packNames() {
  return Object.keys(PACKS)
}

function isValidPack(name) {
  return Object.prototype.hasOwnProperty.call(PACKS, name)
}

// Avoids repeating any word still in `recentWords` unless every word in the
// pack has been used recently (small packs — better a rare repeat than
// getting stuck).
function pickWord(recentWords = [], packName = "default") {
  const words = PACKS[packName] || PACKS.default
  const candidates = words.filter((w) => !recentWords.includes(w))
  const pool = candidates.length > 0 ? candidates : words
  return pool[Math.floor(Math.random() * pool.length)]
}

module.exports = { PACKS, packNames, isValidPack, pickWord }
